#!/bin/bash

# Use commit hook code for this check
source /etc/profile.d/git/git-templates/hooks/lib.sh
source /etc/profile.d/git/git-templates/hooks/config_name_lib.sh

function usage () {
    echo "Usage: $0 '<config name|config file>'" >&2
    exit -1
}

[ -n "$1" ] || usage

if [ -f "$1" ] ; then
    check_config_file "$1" || exit 1
else
    check_config_name "$1" || exit 1
fi

echo "Config name passes checks"
echo "Remember: this just means it doesn't violate any naming standards, but you still need to:"
echo "   1) Make sure it makes sense to have this config"
echo "   2) Make sure the name makes sense for what the config does"
echo "   3) Make sure the description is clear"
