#!/bin/bash

source $GIT_DIR/hooks/lib.sh
source $GIT_DIR/hooks/commit_hook_lib.sh

# Translation should be done either in the database or via the docblock, not using the ->translate()
# function call

# MAIN PROGRAM

get_files_to_check files 'api/controllers' 'AMCR'

# if there are no files, then don't worry about it :)
if [ -z "$files" ] ; then
    exit 0
fi

hook_set_changes_hash "$files"
skip_hook_if_record_matches

offending_files=`ag -l -i "\-\>translate\(" $(echo "$files" | tr '\n' ' ') /dev/null 2>/dev/null`

if ! [ -z "$offending_files" ] ; then
    hook_error "$(
        color_echo red "->translate() should be in the docblock for translated values."
        color_echo yellow "Offending files:"
        print_files "\t" "$offending_files"
    )"
fi

hook_exit
