#!/bin/bash

source $GIT_DIR/hooks/lib.sh
source $GIT_DIR/hooks/commit_hook_lib.sh

# DVO-1174:
#    Remind user if registry.php changed but not includes.php
#

# MAIN PROGRAM

get_files_to_check registry_php 'common/functions/asset_lib/registry.php' 'AMCR'

hook_set_changes_hash "$files"
skip_hook_if_record_matches

if [ -n "$registry_php" ] ; then
    get_files_to_check includes 'common/functions/includes.php' 'AMCR'
    if [ -z "$includes" ] ; then
        hook_error "$(
            color_echo red "You modified common/functions/asset_lib/registry.php but not common/functions/includes.php"
            color_echo yellow "Are you sure this is what you meant to do?"
        )"
    fi
fi

hook_exit
