#!/bin/bash

source $GIT_DIR/hooks/lib.sh
source $GIT_DIR/hooks/commit_hook_lib.sh

# This script checks all api code to make sure that 'select(*)'
# is not called.

# MAIN PROGRAM

get_files_to_check files 'api/' 'AMCR'

# if there are no files, then don't worry about it :)
if [ -z "$files" ] ; then
    exit 0
fi

hook_set_changes_hash "$files"
skip_hook_if_record_matches

offending_files=`ag -l -i "select\(\s+['\"]\*['\"]\s+\)" $(echo "$files" | tr '\n' ' ') /dev/null 2>/dev/null`

if ! [ -z "$offending_files" ] ; then
    hook_error "$(
        color_echo red "Select(*) should not be used!"
        color_echo yellow "Offending files:"
        print_files "\t" "$offending_files"
    )"
fi

hook_exit
