#!/bin/bash

source $GIT_DIR/hooks/lib.sh
source $GIT_DIR/hooks/commit_hook_lib.sh

# DVO-1174:
#    Remind user if common_helpers.php and hadnlebars_helpers.js are not changed together
#

# MAIN PROGRAM

get_files_to_check common_helpers_php 'common/handlebars/common_helpers.php' 'AMCR'
get_files_to_check handlebars_helpers_js 'common/js/handlebars_helpers.js' 'AMCR'

hook_set_changes_hash "$files"
skip_hook_if_record_matches

if [ -n "$common_helpers_php" -o -n "$handlebars_helpers_js" ] ; then
    if [ -z "$common_helpers_php" -o -z "$handlebars_helpers_js" ] ; then
        hook_error "$(
            color_echo red "When you modify one of these files, you should modify both: common/handlebars/common_helpers.php common/js/handlebars_helpers.js"
        )"
    fi
fi

hook_exit
