#!/bin/bash

source $GIT_DIR/hooks/lib.sh
source $GIT_DIR/hooks/commit_hook_lib.sh

# This script ensures that the use of
#   SET protect_keys.enabled = 0;
# over
#   DISABLE TRIGGER tr_protect_keys*

# MAIN PROGRAM

get_files_to_check files 'sql/.*' 'AMR'

# nothing to search for, everything is good
if [[ -z "$files" ]] ; then
    exit 0
fi

hook_set_changes_hash "$files"
skip_hook_if_record_matches

# get the sets of files that potentially violate this commit hook in one way or another
disable_trigger_files=`ag -i 'disable\s+trigger\s+tr_protect_keys' -l $( echo "$files" | tr '\n' ' ') /dev/null 2>/dev/null`

if [[ ! -z "$disable_trigger_files" ]] ; then
    hook_error "$(
        color_echo red 'Prohibited method `DISABLE TRIGGER tr_protect_keys*` used in files:'
        print_files "\t" "$disable_trigger_files"
        echo 'Hint: Use `SET protect_keys.enabled = 0;` instead.'
    )"
fi

hook_exit
