#!/bin/bash

source $GIT_DIR/hooks/lib.sh
source $GIT_DIR/hooks/commit_hook_lib.sh

# This script checks if the SVG src attribute matches the filename

# MAIN PROGRAM

get_files_to_check files '.*[.]svg' 'AMCR'

# if there are no files, then don't worry about it :)
if [ -z "$files" ] ; then
    exit 0
fi

hook_set_changes_hash "$files"
skip_hook_if_record_matches

for file in $files ; do
    # check to make sure the file has the correct 'src' attribute defined
    if ! cat $file | grep -q -P "^\s*src=\"\/$file\"$" ; then
        hook_error "$(
            found_src=`cat $file | grep -o -P '(?<=src=\"\/).+(?=\")'`
            color_echo red "Invalid SVG src attribute found!"
            color_echo yellow "Offending File: $file"
            color_echo yellow "Found Attribute: src=\"/$found_src\""
            color_echo yellow "Expected Atrribute: src=\"/$file\""
        )"
        continue
    fi

done

hook_exit
