#!/bin/bash

source $GIT_DIR/hooks/lib.sh
source $GIT_DIR/hooks/commit_hook_lib.sh
source $GIT_DIR/hooks/config_name_lib.sh

# This script checks edited config/*.json files for:
#   - correct config name

get_files_to_check files '^config/.*[.]json' 'AMCR'

# if there are no files, then don't worry about it :)
if [ -z "$files" ] ; then
    exit 0
fi

hook_set_changes_hash "$files"
skip_hook_if_record_matches

for file in ${files[@]} ; do
    check_config_file "$file"
done

hook_exit
