#!/bin/bash

source $GIT_DIR/hooks/lib.sh
source $GIT_DIR/hooks/commit_hook_lib.sh

# MAIN PROGRAM

get_files_to_check entity_role_location 'api\/|sql\/|perl\/' 'AM'

hook_set_changes_hash "$files"
skip_hook_if_record_matches

if [[ -n $entity_role_location ]]; then
    if $(grep -qP '\btb_entity_role\b|\btb_entity_location\b' $entity_role_location); then
        hook_error "$(
            color_echo red "You used tb_entity_role/tb_entity_location instead of ct_entity_role/vw_entity_location"
            color_echo red "Culprit files:"
            color_echo red "$(grep -PinH '\btb_entity_role\b|\btb_entity_location\b' $entity_role_location)"
            color_echo yellow "Are you sure this is what you meant to do? (Special Tables Wiki: https://neadwerx.atlassian.net/l/c/cn2Yp1ue)"
        )" 
    fi
fi

hook_exit
