#!/bin/bash

source $GIT_DIR/hooks/lib.sh
source $GIT_DIR/hooks/commit_hook_lib.sh

# This script ensures that the user's git config user.name and user.email is set and proper

# MAIN PROGRAM

email=`git config user.email`
name=`git config user.name`

# ensure that the email is set
if [[ -z "$email" ]] ; then
    echo ""

    email=""
    q "What is your @merchlogix.com email address?"
    email="$ANSWER"

    while [[ -z "$email" ]] || echo "$email" | grep -q -v "@merchlogix.com" ; do
        color_echo red "Please provide your neadwerx email address!"
        q "What is your @merchlogix.com email address?"
        email="$ANSWER"
    done

    # set the user's email
    git config --global user.email "$email"
fi

# ensure that the username is set
if [[ -z "$name" ]] ; then
    echo ""

    name=""
    q "What is your First and Last name as it will appear in git?"
    name="$ANSWER"

    while [[ -z "$name" ]] ; do
        color_echo red "Please provide your full name!"
        q "What is your First and Last  name as it will appear in git?"
        name="$ANSWER"
    done

    # set the user's name
    git config --global user.name "$name"
fi

color_echo yellow "Committing as $name <$email>"

hook_exit
