#!/bin/bash

source $GIT_DIR/hooks/lib.sh
source $GIT_DIR/hooks/commit_hook_lib.sh


# This script checks edited php files for:
#   - xerp_test_on_mobile
#   - and asks the comitter if they tested that file

get_files_to_check files '.*[.]php$' 'AMCR'

# if there are no files, then don't worry about it :)
if [ -z "$files" ] ; then
    exit 0
fi

hook_set_changes_hash "$files"
skip_hook_if_record_matches

wiki_link='https://neadwerx.atlassian.net/wiki/x/bwB4L'

for file in ${files[@]} ; do
    if grep -q xerp_test_on_mobile "$file"; then
        ask "Did you test $file using Chrome Mobile View?"
        if [[ $ANSWER != "y" ]] ; then
            color_echo red "Aborting commit: perform test! See wiki:"
            color_echo yellow "\t$wiki_link"
        exit 1;
        fi
    fi
done

hook_exit
~                                                                                        
~                                                                                        
~                                                                                        
~                               
