#!/bin/bash

source $GIT_DIR/hooks/lib.sh
source $GIT_DIR/hooks/commit_hook_lib.sh

# This script checks to make sure you are on the correct PHP version

get_files_to_check files '.*[.]php$' 'AMCR'

# if there are no PHP files, then don't worry about it :)
if [ -z "$files" ] ; then
    exit 0
fi

php -v | grep -q 'PHP 7' || {
    color_echo red "Aborting commit: you must be using PHP 7"
    exit 1;
}

hook_exit
~                                                                                        
~                                                                                        
~                                                                                        
~                               
